/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anu_n
 */
public class ADMINPOSTLOGIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMINPOSTLOGIN
     */
    public ADMINPOSTLOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        WELCOMETEXT1 = new javax.swing.JLabel();
        ADMINWELCOME = new javax.swing.JLabel();
        ADDADMIN = new javax.swing.JButton();
        RESTAURANTOPTIONS = new javax.swing.JButton();
        USEROPTIONS = new javax.swing.JButton();
        USEROPTIONS1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        WELCOMETEXT1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WELCOMETEXT1.setText("WELCOME");

        ADMINWELCOME.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ADMINWELCOME.setText("ADMIN MENU");

        ADDADMIN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ADDADMIN.setText("ADMIN OPTIONS");
        ADDADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDADMINActionPerformed(evt);
            }
        });

        RESTAURANTOPTIONS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RESTAURANTOPTIONS.setText("RESTAURANT OPTIONS");
        RESTAURANTOPTIONS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTAURANTOPTIONSActionPerformed(evt);
            }
        });

        USEROPTIONS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        USEROPTIONS.setText("USER OPTIONS");
        USEROPTIONS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USEROPTIONSActionPerformed(evt);
            }
        });

        USEROPTIONS1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        USEROPTIONS1.setText("ORDERS AND PAYMENTS");
        USEROPTIONS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USEROPTIONS1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADDADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADMINWELCOME, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WELCOMETEXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RESTAURANTOPTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USEROPTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USEROPTIONS1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(WELCOMETEXT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADMINWELCOME)
                .addGap(37, 37, 37)
                .addComponent(ADDADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(RESTAURANTOPTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(USEROPTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(USEROPTIONS1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDADMINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDADMINActionPerformed

    private void RESTAURANTOPTIONSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTAURANTOPTIONSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESTAURANTOPTIONSActionPerformed

    private void USEROPTIONSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USEROPTIONSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USEROPTIONSActionPerformed

    private void USEROPTIONS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USEROPTIONS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USEROPTIONS1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMINPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMINPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMINPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMINPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMINPOSTLOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDADMIN;
    private javax.swing.JLabel ADMINWELCOME;
    private javax.swing.JButton RESTAURANTOPTIONS;
    private javax.swing.JButton USEROPTIONS;
    private javax.swing.JButton USEROPTIONS1;
    private javax.swing.JLabel WELCOMETEXT1;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
