/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anu_n
 */
public class USERPOSTLOGIN extends javax.swing.JFrame {

    /**
     * Creates new form USERPOSTLOGIN
     */
    public USERPOSTLOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PIZZA1 = new javax.swing.JButton();
        BURGER1 = new javax.swing.JButton();
        DRINKS1 = new javax.swing.JButton();
        SPECIAL1 = new javax.swing.JButton();
        PIZZA2 = new javax.swing.JButton();
        BURGER2 = new javax.swing.JButton();
        DRINKS2 = new javax.swing.JButton();
        SPECIAL2 = new javax.swing.JButton();
        SANDWICH1 = new javax.swing.JButton();
        CHINESE1 = new javax.swing.JButton();
        NORTH1 = new javax.swing.JButton();
        SOUTH1 = new javax.swing.JButton();
        PIZZA3 = new javax.swing.JButton();
        BURGER3 = new javax.swing.JButton();
        DRINKS3 = new javax.swing.JButton();
        SPECIAL3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("WHAT DO YOU CRAVE.....?");

        PIZZA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PIZZA.jpg"))); // NOI18N
        PIZZA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIZZA1ActionPerformed(evt);
            }
        });

        BURGER1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BURGER.jpg"))); // NOI18N
        BURGER1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BURGER1ActionPerformed(evt);
            }
        });

        DRINKS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DRINKS.jpg"))); // NOI18N

        SPECIAL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SPECIAL.jpg"))); // NOI18N

        PIZZA2.setText("Pizza");
        PIZZA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIZZA2ActionPerformed(evt);
            }
        });

        BURGER2.setText("Burger");

        DRINKS2.setText("Soft Drinks");

        SPECIAL2.setText("Desserts");
        SPECIAL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPECIAL2ActionPerformed(evt);
            }
        });

        SANDWICH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SANDWICHES.jpg"))); // NOI18N
        SANDWICH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SANDWICH1ActionPerformed(evt);
            }
        });

        CHINESE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHINESE.jpeg"))); // NOI18N

        NORTH1.setBackground(new java.awt.Color(255, 255, 255));
        NORTH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NORTHINDIAN.jpg"))); // NOI18N
        NORTH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NORTH1ActionPerformed(evt);
            }
        });

        SOUTH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IDLIVADA.jpg"))); // NOI18N

        PIZZA3.setText("Sandwich");
        PIZZA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIZZA3ActionPerformed(evt);
            }
        });

        BURGER3.setText("Chinese");

        DRINKS3.setText("North Indian");

        SPECIAL3.setText("South Indian");
        SPECIAL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPECIAL3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PIZZA3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SANDWICH1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PIZZA1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PIZZA2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BURGER1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(DRINKS1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SPECIAL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPECIAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BURGER2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CHINESE1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BURGER3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NORTH1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DRINKS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DRINKS3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SOUTH1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPECIAL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PIZZA1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BURGER1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SPECIAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DRINKS1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PIZZA2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BURGER2)
                        .addComponent(DRINKS2))
                    .addComponent(SPECIAL2))
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CHINESE1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SOUTH1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NORTH1))
                    .addComponent(SANDWICH1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PIZZA3)
                    .addComponent(BURGER3)
                    .addComponent(DRINKS3)
                    .addComponent(SPECIAL3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(658, 658, 658))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(562, 562, 562))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PIZZA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIZZA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIZZA1ActionPerformed

    private void BURGER1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BURGER1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BURGER1ActionPerformed

    private void PIZZA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIZZA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIZZA2ActionPerformed

    private void SPECIAL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPECIAL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPECIAL2ActionPerformed

    private void SANDWICH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SANDWICH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SANDWICH1ActionPerformed

    private void NORTH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NORTH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NORTH1ActionPerformed

    private void PIZZA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIZZA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIZZA3ActionPerformed

    private void SPECIAL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPECIAL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPECIAL3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USERPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USERPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USERPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USERPOSTLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USERPOSTLOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BURGER1;
    private javax.swing.JButton BURGER2;
    private javax.swing.JButton BURGER3;
    private javax.swing.JButton CHINESE1;
    private javax.swing.JButton DRINKS1;
    private javax.swing.JButton DRINKS2;
    private javax.swing.JButton DRINKS3;
    private javax.swing.JButton NORTH1;
    private javax.swing.JButton PIZZA1;
    private javax.swing.JButton PIZZA2;
    private javax.swing.JButton PIZZA3;
    private javax.swing.JButton SANDWICH1;
    private javax.swing.JButton SOUTH1;
    private javax.swing.JButton SPECIAL1;
    private javax.swing.JButton SPECIAL2;
    private javax.swing.JButton SPECIAL3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
